### ISSUE TITLE
Doesn't work in WSL2 Ubuntu 20.04

### ISSUE THREAD

**Issue by Midnex** [jvns/dnspeep#11]
dnspeep: 0.1.1
Windows 10 with WSL2 Ubuntu 20.04 x64

Currently loads but doesn't seem to find anything.

**Comment by jvns** [comment]
Thanks for reporting! If you make DNS queries from inside WSL (for example with `dig example.com`), does it find those?

**Comment by Nomyfan** [comment]
I tried it inside WSL2, it worked.

**Comment by jvns** [comment]
I'm going to close this for now since it seems to be working, feel free to reopen if there's still an issue.
