### ISSUE TITLE
Can dnspeep print out the IP addresses of the DNS query was made from?

### ISSUE THREAD

**Issue by cod1ingcoding** [jvns/dnspeep#13]

**Comment by thomasmerz** [comment]
When running dnspeep it should always catch DNS queries made from the machine on which it's running (localhost/127.0.0.1/::0) - or am I wrong?

If you are running a local DNS resolver like [Pihole](https://github.com/pi-hole/pi-hole) or [AdGuardHome](https://github.com/AdguardTeam/AdGuardHome) than you have the possibility to see in both GUIs which IP address made which DNS queries:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/18568381/113401072-1cf98900-93a3-11eb-80b8-8a55c3523432.png">

**Comment by cod1ingcoding** [comment]
@thomasmerz 
if dnspeep running on a public dns server,  it will catch the dns request from the internet.

**Comment by thomasmerz** [comment]
@cod1ingcoding
I didn't think as big as you did - this is absolutely right 👍🏻
