### ISSUE TITLE
URL wrong for releases in README

### ISSUE THREAD

**Issue by njr0** [jvns/dnspeep#2]
Tiny problem:

On the README you tell people to get releases from <https://github.com/jvns/dnspeep/releases>.

Should be <https://github.com/jvns/dnspeep> (I think).

Thanks for making this!

**Comment by jvns** [comment]
weird, does https://github.com/jvns/dnspeep/releases not link you to the github releases page? it works for me!

**Comment by bostonaholic** [comment]
https://github.com/jvns/dnspeep/releases works for me!

**Comment by njr0** [comment]
OK, that's weird. Yesterday, the link in the README was 404ing for me; today it's not.  ¯\_(ツ)_/¯.

Will close; apologies for the misdirection.
