### ISSUE TITLE
RFE: source process and response time

### ISSUE THREAD

**Issue by badnetmask** [jvns/dnspeep#3]
Thanks for this project! It sure makes life a lot easier, so I don't need to remember the BPF syntax.

I would like to ask for two enhancements, if possible:
a) The source name or PID of the process which generated the query.
b) The time that it took to receive the response.

Thank you!

**Comment by thomasmerz** [comment]
I would also appreciate a **timestamp before every line**.
Actually I use this "hack" from https://www.commandlinefu.com/commands/view/2682/vmstatiostat-with-timestamp
`sudo dnspeep | awk '{now=strftime("%Y-%m-%d %T "); print now $0}'`

Sould I open a new RFE or is it also ok to be included here?

**Comment by jvns** [comment]
A `-t` flag to timestamp every line and the time it took to receive each response both make sense to me!

Getting the PID of the process with generate the query is a little trickier -- I think I know how to do it on Linux (using BPF) but I don't know how to do it on Mac.

**Comment by thomasmerz** [comment]
There's also BPF on MacOS 🤔

**Comment by jvns** [comment]
Oh, I mean eBPF (https://ebpf.io/)

**Comment by thomasmerz** [comment]
Have you seen [User Space eBPF](https://github.com/zoidbergwill/awesome-ebpf#user-space-ebpf) and [Rust (user-space) virtual machine for eBPF](https://github.com/qmonnet/rbpf) in detail?

**Comment by jvns** [comment]
Added a `-t` flag to print out the timestamp so I'm going to close this. I'll open another issue to track the other idea.

**Comment by badnetmask** [comment]
It works great! Thank you!
