### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by EmRowlands** [jvns/dnspeep#4]
I am packaging this project, and I would like to know the license for the code. I've looked around in all the usual places but I can't find any indication of any particular license. Various dependencies have the licenses "Apache-2.0 BSD-3-Clause ISC MIT Unlicense", but I can't find anything for this project.

**Comment by jvns** [comment]
Fixed, thanks! (where are you packaging it, out of curiosity?)

**Comment by EmRowlands** [comment]
I'm packaging for my personal Gentoo overlay, you can see the files and details here: https://gitlab.com/EmRowlands/erowl-overlay/-/tree/main/net-dns/dnspeep
