### ISSUE TITLE
Index out of bounds panic in main.rs:153:21

### ISSUE THREAD

**Issue by siebenmann** [jvns/dnspeep#5]
Running dnspeep on a Fedora 33 machine with both IPv4 and IPv6 connectivity I can sometimes see queries but then sooner or later I get:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:153:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The backtrace doesn't seem to be very useful; it appears to be failing where it says it's failing, in the line:
```
    let question = &dns_packet.questions[0];
```
This seems to be the result of the authoritative DNS server I'm running on this machine answering a query by telling the sender to go away (I think):
```
In  IP [RANDOM-IP].30279 > [MYIP].domain: 5140+ [1au] ANY? . (33)
Out IP [MYIP].domain > [RANDOM-IP].30279: 5140-| [0q] 0/0/1 (23)
```
Wireshark confirms that the relevant DNS reply packet has no questions, no answer RRs, no authority RRs, and one additional RR of type OPT.

(This has already been useful, I had no idea people were spraying my authoritative nameserver with these queries.)

**Comment by jvns** [comment]
Thanks for reporting! I made a PR to fix this in #6 -- can you test if it works?

I'd also love a pcap file (only if there's no private data in it of course) so I can eventually add some tests for this case.

**Comment by siebenmann** [comment]
This still panics, but now slightly later:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:157:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think this is happening because dnspeep is seeing an answer (with no questions) for a query that it didn't see, and so is trying to insert the answer into the id map. I suspect that perhaps the code should look for the 'this is a response' flag and skip adding those to the map, whether or not they've got a question in them. Looking at the documentation for dns-parse, it looks like this is the 'query' bool in the header, so `dns_packet.header.query` in your code.

I think this raises another issue, which is that the current code appears to assume that queries are never repeated with identical IDs. If they are, I believe the second time around dnspeep will think that it has an answer.

Also, the new PR appears to sometimes put quotes around the query (type) in the output, eg printing `"MX"` instead of just `MX`.

**Comment by jvns** [comment]
Can you share a pcap file of some DNS queries that cause the problem? It'll be easiest for me to reproduce and fix the issue with a pcap file. You can get one with 

```
sudo tcpdump -i any port 53 -c 100 -w dns_packets.pcap
```

You can email it to julia@jvns.ca if you don't want to post it to github.

**Comment by jvns** [comment]
@siebenmann Can you try #6 again? I refactored all of the query tracking logic and I think it makes a lot more sense now (and will be a lot less buggy). I rebased it on master and force pushed so you might have to delete your local branch.

I also added a feature to replay pcap files and tested it by replaying the pcap file you sent me (`dnspeep -f dns_packets.pcap`) and it doesn't crash anymore on that pcap file.

**Comment by siebenmann** [comment]
It looks good to me. I left `dnspeep` running for a fair while without any panics, and all of the output looked correct (and well formatted).
